import shutil
from collections.abc import Generator
from contextlib import contextmanager  # noqa: I001
from pathlib import Path

from pyqualw2 import model_runner
from pyqualw2.config.config import Config


@contextmanager
def cp_cequalw2_binary(path: Path | str) -> Generator[Path]:
    """Temporarily copy the cequalw2 w2_v45_64.exe binary to the target directory.

    Parameters
    ----------
    path : Path | str
        Path to copy the binary to; this should also be where the input data is
    """
    path = Path(path)
    binary = Path(__file__).parent.parent / "cequalw2" / "w2_v45_64.exe"
    shutil.copy(binary, path)
    yield path
    (path / "w2_v45_64.exe").unlink()


def test_model_runner(
    tmp_path,
    sample_w2_con,
    sample_bathymetry,
    sample_profile,
    sample_temp_2018,
    sample_met_2018,
    sample_flow_2018,
):
    """Test the ModelRunner class."""
    config = Config.from_files(
        sample_w2_con,
        sample_bathymetry,
        sample_profile,
        sample_temp_2018,
        sample_met_2018,
        sample_flow_2018,
    )

    test_dir = Path(__file__).parent.parent / "test" / "sample_data1"
    with cp_cequalw2_binary(test_dir):
        Runner = model_runner.ModelRunner(config, tmp_path, test_dir, "test_run")
        Runner.run()

        # Input files
        expected_file_list = set()
        for file in test_dir.iterdir():
            expected_file_list.add(file.name)

        # Simulation run directory
        conf_dir = tmp_path / "test_run"
        conf_output_files = set()
        for file in conf_dir.iterdir():
            conf_output_files.add(file.name)

        # The simulation run directory should contain the input files in addition
        # to the output data generated by the cequalw2
        assert expected_file_list < conf_output_files
